### ISSUE TITLE
Inject Container within itself.

### ISSUE THREAD

**Issue by thohoh** [typesoft/container-ioc#70]
Container should be available for injections into members it contains (service locator anti pattern). Auto register container within itself when instantiating.

- [ ] Write tests first, every member of a container should be able to inject container they're inside of. `class B { constructor(@Inject(TContainer) private container: IContainer) {}  }`

- [ ] create container type  TContainer =  Symbol('IContainer')` next to IContainer in the same file.

- [ ] when instantiating a new container, that container instance should register itself within itself via TContainer type ( `this.register({ token: TContainer, useValue: this })`

- [ ] Create an example file for typescript and javascript.

**Comment by thohoh** [comment]
Auto register container within itself. 
Give default type for Container. 
`export const TContainer =  Symbol('IContainer')`

**Comment by Tolowe** [comment]
Hey there again, I'm going to give this one a shot if that's OK. I think I understand the goal of this issue. I may reach out with some questions at some point.
