### ISSUE TITLE
Deprecate InjectionToken

### ISSUE THREAD

**Issue by thohoh** [typesoft/container-ioc#87]
mark InjectionToken entity as deprecated. (Will be removed in future releases).

put /* @deprecated */ comment right above the class

**Comment by thohoh** [comment]
Remove from the project.

**Comment by Tolowe** [comment]
Hey there - found this site via up for grabs. This seems fairly easy for my first attempt at a fork, going to give it a shot if you don't mind. Still just wanting to deprecate this class with the comment above? Going to submit a pull request for that.
